// Code generated by MockGen. DO NOT EDIT.
// Source: external/cloudinary/claudinary.go

// Package mock_cloudinary is a generated GoMock package.
package mocks

import (
	multipart "mime/multipart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCloudinaryService is a mock of CloudinaryService interface.
type MockCloudinaryService struct {
	ctrl     *gomock.Controller
	recorder *MockCloudinaryServiceMockRecorder
}

// MockCloudinaryServiceMockRecorder is the mock recorder for MockCloudinaryService.
type MockCloudinaryServiceMockRecorder struct {
	mock *MockCloudinaryService
}

// NewMockCloudinaryService creates a new mock instance.
func NewMockCloudinaryService(ctrl *gomock.Controller) *MockCloudinaryService {
	mock := &MockCloudinaryService{ctrl: ctrl}
	mock.recorder = &MockCloudinaryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudinaryService) EXPECT() *MockCloudinaryServiceMockRecorder {
	return m.recorder
}

// UploadImage mocks base method.
func (m *MockCloudinaryService) UploadImage(fileHeader *multipart.FileHeader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", fileHeader)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockCloudinaryServiceMockRecorder) UploadImage(fileHeader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockCloudinaryService)(nil).UploadImage), fileHeader)
}
