// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/department_repository.go

// Package mock_repository is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/manciniraka/urbioxe/internal/entity"
)

// MockDepartmentRepository is a mock of DepartmentRepository interface.
type MockDepartmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentRepositoryMockRecorder
}

// MockDepartmentRepositoryMockRecorder is the mock recorder for MockDepartmentRepository.
type MockDepartmentRepositoryMockRecorder struct {
	mock *MockDepartmentRepository
}

// NewMockDepartmentRepository creates a new mock instance.
func NewMockDepartmentRepository(ctrl *gomock.Controller) *MockDepartmentRepository {
	mock := &MockDepartmentRepository{ctrl: ctrl}
	mock.recorder = &MockDepartmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentRepository) EXPECT() *MockDepartmentRepositoryMockRecorder {
	return m.recorder
}

// CheckCodeOrNameExists mocks base method.
func (m *MockDepartmentRepository) CheckCodeOrNameExists(code, name string, excludeID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCodeOrNameExists", code, name, excludeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCodeOrNameExists indicates an expected call of CheckCodeOrNameExists.
func (mr *MockDepartmentRepositoryMockRecorder) CheckCodeOrNameExists(code, name, excludeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCodeOrNameExists", reflect.TypeOf((*MockDepartmentRepository)(nil).CheckCodeOrNameExists), code, name, excludeID)
}

// Create mocks base method.
func (m *MockDepartmentRepository) Create(department *entity.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", department)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDepartmentRepositoryMockRecorder) Create(department interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDepartmentRepository)(nil).Create), department)
}

// FindAll mocks base method.
func (m *MockDepartmentRepository) FindAll(isOnlyActive bool) ([]entity.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", isOnlyActive)
	ret0, _ := ret[0].([]entity.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockDepartmentRepositoryMockRecorder) FindAll(isOnlyActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockDepartmentRepository)(nil).FindAll), isOnlyActive)
}

// FindByID mocks base method.
func (m *MockDepartmentRepository) FindByID(id uint) (*entity.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*entity.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDepartmentRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDepartmentRepository)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockDepartmentRepository) Update(department *entity.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", department)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDepartmentRepositoryMockRecorder) Update(department interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDepartmentRepository)(nil).Update), department)
}

// UpdateStatus mocks base method.
func (m *MockDepartmentRepository) UpdateStatus(id uint, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", id, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDepartmentRepositoryMockRecorder) UpdateStatus(id, isActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDepartmentRepository)(nil).UpdateStatus), id, isActive)
}
