// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/district_repository.go

// Package mock_repository is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/manciniraka/urbioxe/internal/entity"
)

// MockDistrictRepository is a mock of DistrictRepository interface.
type MockDistrictRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDistrictRepositoryMockRecorder
}

// MockDistrictRepositoryMockRecorder is the mock recorder for MockDistrictRepository.
type MockDistrictRepositoryMockRecorder struct {
	mock *MockDistrictRepository
}

// NewMockDistrictRepository creates a new mock instance.
func NewMockDistrictRepository(ctrl *gomock.Controller) *MockDistrictRepository {
	mock := &MockDistrictRepository{ctrl: ctrl}
	mock.recorder = &MockDistrictRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDistrictRepository) EXPECT() *MockDistrictRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDistrictRepository) Create(district *entity.District) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", district)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDistrictRepositoryMockRecorder) Create(district interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDistrictRepository)(nil).Create), district)
}

// GetAll mocks base method.
func (m *MockDistrictRepository) GetAll() ([]entity.District, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]entity.District)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDistrictRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDistrictRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockDistrictRepository) GetByID(id uint) (*entity.District, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.District)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDistrictRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDistrictRepository)(nil).GetByID), id)
}

// GetByName mocks base method.
func (m *MockDistrictRepository) GetByName(name string) (*entity.District, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name)
	ret0, _ := ret[0].(*entity.District)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockDistrictRepositoryMockRecorder) GetByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockDistrictRepository)(nil).GetByName), name)
}

// Update mocks base method.
func (m *MockDistrictRepository) Update(district *entity.District) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", district)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDistrictRepositoryMockRecorder) Update(district interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDistrictRepository)(nil).Update), district)
}
