// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/emergency_repository.go

// Package mock_repository is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/manciniraka/urbioxe/internal/entity"
)

// MockEmergencyRepository is a mock of EmergencyRepository interface.
type MockEmergencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmergencyRepositoryMockRecorder
}

// MockEmergencyRepositoryMockRecorder is the mock recorder for MockEmergencyRepository.
type MockEmergencyRepositoryMockRecorder struct {
	mock *MockEmergencyRepository
}

// NewMockEmergencyRepository creates a new mock instance.
func NewMockEmergencyRepository(ctrl *gomock.Controller) *MockEmergencyRepository {
	mock := &MockEmergencyRepository{ctrl: ctrl}
	mock.recorder = &MockEmergencyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmergencyRepository) EXPECT() *MockEmergencyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEmergencyRepository) Create(emergency *entity.EmergencyContact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", emergency)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEmergencyRepositoryMockRecorder) Create(emergency interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmergencyRepository)(nil).Create), emergency)
}

// GetAll mocks base method.
func (m *MockEmergencyRepository) GetAll() ([]entity.EmergencyContact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]entity.EmergencyContact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockEmergencyRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockEmergencyRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockEmergencyRepository) GetByID(id uint) (*entity.EmergencyContact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.EmergencyContact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEmergencyRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEmergencyRepository)(nil).GetByID), id)
}

// Update mocks base method.
func (m *MockEmergencyRepository) Update(emergency *entity.EmergencyContact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", emergency)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEmergencyRepositoryMockRecorder) Update(emergency interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEmergencyRepository)(nil).Update), emergency)
}
