// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/meter_reading_repository.go

// Package mock_repository is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/manciniraka/urbioxe/internal/entity"
)

// MockMeterReadingRepository is a mock of MeterReadingRepository interface.
type MockMeterReadingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMeterReadingRepositoryMockRecorder
}

// MockMeterReadingRepositoryMockRecorder is the mock recorder for MockMeterReadingRepository.
type MockMeterReadingRepositoryMockRecorder struct {
	mock *MockMeterReadingRepository
}

// NewMockMeterReadingRepository creates a new mock instance.
func NewMockMeterReadingRepository(ctrl *gomock.Controller) *MockMeterReadingRepository {
	mock := &MockMeterReadingRepository{ctrl: ctrl}
	mock.recorder = &MockMeterReadingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeterReadingRepository) EXPECT() *MockMeterReadingRepositoryMockRecorder {
	return m.recorder
}

// CreateMeterReading mocks base method.
func (m *MockMeterReadingRepository) CreateMeterReading(meterReading *entity.MeterReading) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMeterReading", meterReading)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMeterReading indicates an expected call of CreateMeterReading.
func (mr *MockMeterReadingRepositoryMockRecorder) CreateMeterReading(meterReading interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMeterReading", reflect.TypeOf((*MockMeterReadingRepository)(nil).CreateMeterReading), meterReading)
}

// GetAllMeterReadings mocks base method.
func (m *MockMeterReadingRepository) GetAllMeterReadings(month, year *int) ([]entity.MeterReading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMeterReadings", month, year)
	ret0, _ := ret[0].([]entity.MeterReading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMeterReadings indicates an expected call of GetAllMeterReadings.
func (mr *MockMeterReadingRepositoryMockRecorder) GetAllMeterReadings(month, year interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMeterReadings", reflect.TypeOf((*MockMeterReadingRepository)(nil).GetAllMeterReadings), month, year)
}

// GetMyMeterReadings mocks base method.
func (m *MockMeterReadingRepository) GetMyMeterReadings(userID uint) ([]entity.MeterReading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyMeterReadings", userID)
	ret0, _ := ret[0].([]entity.MeterReading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyMeterReadings indicates an expected call of GetMyMeterReadings.
func (mr *MockMeterReadingRepositoryMockRecorder) GetMyMeterReadings(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyMeterReadings", reflect.TypeOf((*MockMeterReadingRepository)(nil).GetMyMeterReadings), userID)
}
