// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/report_repository.go

// Package mock_repository is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/manciniraka/urbioxe/internal/entity"
	repository "github.com/manciniraka/urbioxe/internal/repository"
)

// MockReportRepository is a mock of ReportRepository interface.
type MockReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepositoryMockRecorder
}

// MockReportRepositoryMockRecorder is the mock recorder for MockReportRepository.
type MockReportRepositoryMockRecorder struct {
	mock *MockReportRepository
}

// NewMockReportRepository creates a new mock instance.
func NewMockReportRepository(ctrl *gomock.Controller) *MockReportRepository {
	mock := &MockReportRepository{ctrl: ctrl}
	mock.recorder = &MockReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportRepository) EXPECT() *MockReportRepositoryMockRecorder {
	return m.recorder
}

// AssignStaff mocks base method.
func (m *MockReportRepository) AssignStaff(reportID, staffID, actorID uint, notes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignStaff", reportID, staffID, actorID, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignStaff indicates an expected call of AssignStaff.
func (mr *MockReportRepositoryMockRecorder) AssignStaff(reportID, staffID, actorID, notes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignStaff", reflect.TypeOf((*MockReportRepository)(nil).AssignStaff), reportID, staffID, actorID, notes)
}

// Create mocks base method.
func (m *MockReportRepository) Create(report *entity.Report) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", report)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReportRepositoryMockRecorder) Create(report interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReportRepository)(nil).Create), report)
}

// FindAll mocks base method.
func (m *MockReportRepository) FindAll(filter repository.ReportFilter) ([]entity.Report, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", filter)
	ret0, _ := ret[0].([]entity.Report)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockReportRepositoryMockRecorder) FindAll(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockReportRepository)(nil).FindAll), filter)
}

// FindByID mocks base method.
func (m *MockReportRepository) FindByID(id uint, role string) (*entity.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id, role)
	ret0, _ := ret[0].(*entity.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockReportRepositoryMockRecorder) FindByID(id, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockReportRepository)(nil).FindByID), id, role)
}

// ResolveReport mocks base method.
func (m *MockReportRepository) ResolveReport(reportID, actorID uint, notes string, attachments []entity.ReportAttachment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveReport", reportID, actorID, notes, attachments)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveReport indicates an expected call of ResolveReport.
func (mr *MockReportRepositoryMockRecorder) ResolveReport(reportID, actorID, notes, attachments interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveReport", reflect.TypeOf((*MockReportRepository)(nil).ResolveReport), reportID, actorID, notes, attachments)
}

// Update mocks base method.
func (m *MockReportRepository) Update(report *entity.Report) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", report)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockReportRepositoryMockRecorder) Update(report interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReportRepository)(nil).Update), report)
}

// UpdatePriorityWithHistory mocks base method.
func (m *MockReportRepository) UpdatePriorityWithHistory(reportID uint, status entity.ReportStatus, newPriority entity.ReportPriority, actorID uint, notes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePriorityWithHistory", reportID, status, newPriority, actorID, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePriorityWithHistory indicates an expected call of UpdatePriorityWithHistory.
func (mr *MockReportRepositoryMockRecorder) UpdatePriorityWithHistory(reportID, status, newPriority, actorID, notes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePriorityWithHistory", reflect.TypeOf((*MockReportRepository)(nil).UpdatePriorityWithHistory), reportID, status, newPriority, actorID, notes)
}

// UpdateStatusWithHistory mocks base method.
func (m *MockReportRepository) UpdateStatusWithHistory(reportID uint, newStatus entity.ReportStatus, actorID uint, notes string, isInternal bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusWithHistory", reportID, newStatus, actorID, notes, isInternal)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusWithHistory indicates an expected call of UpdateStatusWithHistory.
func (mr *MockReportRepositoryMockRecorder) UpdateStatusWithHistory(reportID, newStatus, actorID, notes, isInternal interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusWithHistory", reflect.TypeOf((*MockReportRepository)(nil).UpdateStatusWithHistory), reportID, newStatus, actorID, notes, isInternal)
}
