// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/staff_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/staff_repository.go -destination=mocks/staff_mock_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	entity "github.com/manciniraka/urbioxe/internal/entity"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockStaffRepository is a mock of StaffRepository interface.
type MockStaffRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStaffRepositoryMockRecorder
	isgomock struct{}
}

// MockStaffRepositoryMockRecorder is the mock recorder for MockStaffRepository.
type MockStaffRepositoryMockRecorder struct {
	mock *MockStaffRepository
}

// NewMockStaffRepository creates a new mock instance.
func NewMockStaffRepository(ctrl *gomock.Controller) *MockStaffRepository {
	mock := &MockStaffRepository{ctrl: ctrl}
	mock.recorder = &MockStaffRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaffRepository) EXPECT() *MockStaffRepositoryMockRecorder {
	return m.recorder
}

// CreateStaffTx mocks base method.
func (m *MockStaffRepository) CreateStaffTx(tx *gorm.DB, staff *entity.StaffProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStaffTx", tx, staff)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStaffTx indicates an expected call of CreateStaffTx.
func (mr *MockStaffRepositoryMockRecorder) CreateStaffTx(tx, staff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStaffTx", reflect.TypeOf((*MockStaffRepository)(nil).CreateStaffTx), tx, staff)
}

// FindStaffByUserID mocks base method.
func (m *MockStaffRepository) FindStaffByUserID(userID uint) (*entity.StaffProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStaffByUserID", userID)
	ret0, _ := ret[0].(*entity.StaffProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStaffByUserID indicates an expected call of FindStaffByUserID.
func (mr *MockStaffRepositoryMockRecorder) FindStaffByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStaffByUserID", reflect.TypeOf((*MockStaffRepository)(nil).FindStaffByUserID), userID)
}

// GetAll mocks base method.
func (m *MockStaffRepository) GetAll() ([]entity.StaffProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]entity.StaffProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockStaffRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockStaffRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockStaffRepository) GetByID(id uint) (*entity.StaffProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.StaffProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStaffRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStaffRepository)(nil).GetByID), id)
}

// GetLastEmployeeSequence mocks base method.
func (m *MockStaffRepository) GetLastEmployeeSequence(departmentID uint, joinDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastEmployeeSequence", departmentID, joinDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastEmployeeSequence indicates an expected call of GetLastEmployeeSequence.
func (mr *MockStaffRepositoryMockRecorder) GetLastEmployeeSequence(departmentID, joinDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastEmployeeSequence", reflect.TypeOf((*MockStaffRepository)(nil).GetLastEmployeeSequence), departmentID, joinDate)
}

// UpdateStaffTx mocks base method.
func (m *MockStaffRepository) UpdateStaffTx(tx *gorm.DB, staff *entity.StaffProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStaffTx", tx, staff)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStaffTx indicates an expected call of UpdateStaffTx.
func (mr *MockStaffRepositoryMockRecorder) UpdateStaffTx(tx, staff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStaffTx", reflect.TypeOf((*MockStaffRepository)(nil).UpdateStaffTx), tx, staff)
}
