// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/water_repository.go

// Package mock_repository is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/manciniraka/urbioxe/internal/entity"
)

// MockWaterRepository is a mock of WaterRepository interface.
type MockWaterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWaterRepositoryMockRecorder
}

// MockWaterRepositoryMockRecorder is the mock recorder for MockWaterRepository.
type MockWaterRepositoryMockRecorder struct {
	mock *MockWaterRepository
}

// NewMockWaterRepository creates a new mock instance.
func NewMockWaterRepository(ctrl *gomock.Controller) *MockWaterRepository {
	mock := &MockWaterRepository{ctrl: ctrl}
	mock.recorder = &MockWaterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWaterRepository) EXPECT() *MockWaterRepositoryMockRecorder {
	return m.recorder
}

// CreateWaterStatus mocks base method.
func (m *MockWaterRepository) CreateWaterStatus(waterStatus *entity.WaterStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWaterStatus", waterStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWaterStatus indicates an expected call of CreateWaterStatus.
func (mr *MockWaterRepositoryMockRecorder) CreateWaterStatus(waterStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWaterStatus", reflect.TypeOf((*MockWaterRepository)(nil).CreateWaterStatus), waterStatus)
}

// GetLatestAllWaterStatus mocks base method.
func (m *MockWaterRepository) GetLatestAllWaterStatus() ([]entity.WaterStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestAllWaterStatus")
	ret0, _ := ret[0].([]entity.WaterStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestAllWaterStatus indicates an expected call of GetLatestAllWaterStatus.
func (mr *MockWaterRepositoryMockRecorder) GetLatestAllWaterStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestAllWaterStatus", reflect.TypeOf((*MockWaterRepository)(nil).GetLatestAllWaterStatus))
}

// GetLatestWaterStatusByDistrictID mocks base method.
func (m *MockWaterRepository) GetLatestWaterStatusByDistrictID(districtID uint) (*entity.WaterStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestWaterStatusByDistrictID", districtID)
	ret0, _ := ret[0].(*entity.WaterStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestWaterStatusByDistrictID indicates an expected call of GetLatestWaterStatusByDistrictID.
func (mr *MockWaterRepositoryMockRecorder) GetLatestWaterStatusByDistrictID(districtID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestWaterStatusByDistrictID", reflect.TypeOf((*MockWaterRepository)(nil).GetLatestWaterStatusByDistrictID), districtID)
}

// GetWaterStatusHistories mocks base method.
func (m *MockWaterRepository) GetWaterStatusHistories() ([]entity.WaterStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWaterStatusHistories")
	ret0, _ := ret[0].([]entity.WaterStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWaterStatusHistories indicates an expected call of GetWaterStatusHistories.
func (mr *MockWaterRepositoryMockRecorder) GetWaterStatusHistories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWaterStatusHistories", reflect.TypeOf((*MockWaterRepository)(nil).GetWaterStatusHistories))
}
